import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"
import type { Json } from "@/lib/supabase/types"

export async function POST(request: Request) {
  const supabase = await createClient()
  const formData = await request.formData()

  const transactionId = formData.get("transaction_id") as string
  const assetType = formData.get("asset_type") as string
  const trackingMode = formData.get("tracking_mode") as string
  const serialNumber = formData.get("serial_number") as string
  const manufacturer = formData.get("manufacturer") as string
  const model = formData.get("model") as string
  const assetTag = formData.get("asset_tag") as string
  const quantityStr = formData.get("quantity") as string
  const weightStr = formData.get("weight") as string
  const notes = formData.get("notes") as string

  // Validation
  const fieldErrors: Record<string, string> = {}
  if (!transactionId?.trim()) fieldErrors.transaction_id = "Transaction is required"
  if (!assetType?.trim()) fieldErrors.asset_type = "Asset type is required"
  if (Object.keys(fieldErrors).length > 0) {
    return NextResponse.json(
      { success: false, error: "Validation failed", fieldErrors },
      { status: 400 },
    )
  }

  const quantity = quantityStr ? parseInt(quantityStr, 10) : 1
  const weight = weightStr ? parseFloat(weightStr) : null

  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json(
      { success: false, error: "Not authenticated" },
      { status: 401 },
    )
  }

  // 1. Create asset record (internal_asset_id auto-generated by DB trigger)
  const { data: asset, error: assetError } = await supabase
    .from("assets")
    .insert({
      transaction_id: transactionId,
      asset_type: assetType as
        | "desktop"
        | "server"
        | "laptop"
        | "monitor"
        | "printer"
        | "phone"
        | "tv"
        | "network"
        | "other",
      tracking_mode: (trackingMode || "serialized") as "serialized" | "bulk",
      serial_number: serialNumber?.trim() || null,
      manufacturer: manufacturer?.trim() || null,
      model: model?.trim() || null,
      asset_tag: assetTag?.trim() || null,
      quantity,
      weight,
      notes: notes?.trim() || null,
      status: "received",
      created_by: user.id,
    })
    .select(
      "id, internal_asset_id, serial_number, asset_type, manufacturer, model",
    )
    .single()

  if (assetError) {
    return NextResponse.json(
      { success: false, error: assetError.message },
      { status: 500 },
    )
  }

  // 2. Create inventory record
  const { data: inventory } = await supabase
    .from("inventory")
    .insert({
      asset_id: asset.id,
      description:
        [asset.manufacturer, asset.model].filter(Boolean).join(" ") ||
        asset.asset_type,
      location: "RECEIVING",
      quantity_on_hand: quantity,
      unit_of_measure: "EA",
      status: "in_process" as const,
    })
    .select("id")
    .single()

  // 3. Get transaction number for journal reference
  const { data: txn } = await supabase
    .from("transactions")
    .select("transaction_number")
    .eq("id", transactionId)
    .single()

  // 4. Create inventory journal receipt entry
  if (inventory) {
    await supabase.from("inventory_journal").insert({
      inventory_id: inventory.id,
      asset_id: asset.id,
      transaction_id: transactionId,
      movement_type: "receipt" as const,
      quantity,
      to_location: "RECEIVING",
      reference_number: txn?.transaction_number ?? null,
      reason: "Initial intake",
      performed_by: user.id,
    })
  }

  // 5. Log initial status history
  await supabase.from("asset_status_history").insert({
    asset_id: asset.id,
    previous_status: null,
    new_status: "received",
    reason_for_change: "Initial intake",
    explanation: `Asset received via transaction ${txn?.transaction_number ?? transactionId}`,
    changed_by: user.id,
  })

  // 6. Evaluate routing rules
  let suggestedDisposition: string | null = null
  let ruleMatch: string | null = null

  const { data: rules } = await supabase
    .from("routing_rules")
    .select("*")
    .eq("is_active", true)
    .order("priority", { ascending: false })

  if (rules) {
    for (const rule of rules) {
      const conditions = rule.conditions as Record<string, Json>
      if (
        matchesConditions(conditions, {
          asset_type: assetType,
          manufacturer: manufacturer?.trim() || null,
          model: model?.trim() || null,
          tracking_mode: trackingMode || "serialized",
        })
      ) {
        suggestedDisposition = rule.action
        ruleMatch = rule.name
        break
      }
    }
  }

  return NextResponse.json({
    success: true,
    asset,
    suggestedDisposition,
    ruleMatch,
  })
}

function matchesConditions(
  conditions: Record<string, Json>,
  asset: Record<string, string | null>,
): boolean {
  for (const [key, expected] of Object.entries(conditions)) {
    if (key === "asset_type" && expected !== asset.asset_type) return false
    if (key === "asset_type_in") {
      const types = expected as string[]
      if (!types.includes(asset.asset_type ?? "")) return false
    }
    if (key === "manufacturer" && expected !== asset.manufacturer) return false
    if (key === "tracking_mode" && expected !== asset.tracking_mode) return false
  }
  return true
}
