-- DispoTrack — Seed Clients
-- Run in Supabase SQL Editor

INSERT INTO public.clients (account_number, name, cost_center, address1, address2, city, state, zip, contact_name, contact_email, contact_phone, notes) VALUES
  ('BA0400', 'Baptist Memorial Health Care', 'IT-SURPLUS', '350 North Humphreys Blvd', NULL, 'Memphis', 'TN', '38120', 'Kevin Barnett', 'kbarnett@baptistonline.org', '901-555-0312', 'Large hospital system. Quarterly bulk pickups. HIPAA destruction required. All drives must be shredded.'),
  ('NR0500', 'Northrop Realty Group', 'CORP-IT', '2100 Lakeland Drive', 'Suite 400', 'Jackson', 'MS', '39232', 'Dana Okafor', 'dokafor@northroprealty.com', '601-555-0198', 'Real estate firm. Small monthly volumes — mostly desktops and monitors. Net-45 terms.'),
  ('CS0600', 'Consolidated Steel Inc', 'MAINT-IT', '8700 Industrial Parkway', NULL, 'Bessemer', 'AL', '35022', 'James Trudeau', 'jtrudeau@consteel.com', '205-555-0467', 'Manufacturing facility. Rugged equipment — expect heavy cosmetic wear. Mostly network gear and servers.'),
  ('PV0700', 'Pine Valley School District', 'TECH-DEPT', '1400 Pine Valley Road', NULL, 'Columbus', 'MS', '39702', 'Angela Moss', 'amoss@pinevalleysd.edu', '662-555-0721', 'K-12 district. Annual summer refresh — 200-400 laptops per cycle. Chromebooks and Dell Latitudes. Student data wipe certification required.'),
  ('WH0800', 'Whitfield Foods LLC', 'OPERATIONS', '5500 Highway 45 North', 'Building C', 'Meridian', 'MS', '39301', 'Robert Shin', 'rshin@whitfieldfoods.com', '601-555-0589', 'Food processing company. Stainless environments — corrosion on some units. Printers and phones mostly.'),
  ('AT0900', 'Atlas Telecom Partners', 'DECOM', '3300 Poplar Avenue', 'Floor 12', 'Memphis', 'TN', '38111', 'Lisa Fontaine', 'lfontaine@atlastelecom.net', '901-555-0843', 'Telecom provider. High volume network equipment — switches, routers, rack-mount servers. Half-rack and full-rack units.'),
  ('GC1000', 'Gulf Coast Credit Union', 'IT-SEC', '900 Beach Boulevard', NULL, 'Biloxi', 'MS', '39530', 'Tony Ramirez', 'tramirez@gulfcoastcu.org', '228-555-0156', 'Financial institution. PCI compliance required. All drives must be destroyed with certificate. Monthly pickups.'),
  ('DM1100', 'Delta Medical Center', 'BIO-IT', '2700 Highway 61 North', NULL, 'Greenville', 'MS', '38701', 'Patricia Huang', 'phuang@deltamedical.org', '662-555-0934', 'Rural hospital. Mix of clinical workstations and admin PCs. HIPAA wipe required. Bi-monthly pickup schedule.'),
  ('SR1200', 'Summit Ridge Energy', 'FIELD-OPS', '4100 Energy Plaza', 'Suite 200', 'Tuscaloosa', 'AL', '35401', 'Derek Volkov', 'dvolkov@summitridge.energy', '205-555-0672', 'Energy company. Field laptops in rough condition. Some ruggedized units (Panasonic Toughbooks). Quarterly dispositions.'),
  ('LX1300', 'Luxe Hospitality Group', 'CORP-TECH', '1200 Convention Center Blvd', NULL, 'New Orleans', 'LA', '70130', 'Michelle Tran', 'mtran@luxehospitality.com', '504-555-0418', 'Hotel management company. POS terminals, lobby kiosks, back-office PCs. Annual refresh across 12 properties.');
